//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace task03_0606.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Cartes = new HashSet<Carte>();
            this.Feedbacks = new HashSet<Feedback>();
            this.OrderDetials = new HashSet<OrderDetial>();
        }
    
        public int productID { get; set; }
        public string productName { get; set; }
        public string productPicture { get; set; }
        public Nullable<int> salesVolume { get; set; }
        public string storeProductId { get; set; }
        public string productDescription { get; set; }
        public int productPrice { get; set; }
        public string storeId { get; set; }
        public int productState { get; set; }
        public int categoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carte> Cartes { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetial> OrderDetials { get; set; }
        public virtual Store Store { get; set; }
    }
}
