//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace task03_0606.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userInfo
    {
        public int id { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string userId { get; set; }
        public string email { get; set; }
        public string pwd { get; set; }
        public string phoneNum { get; set; }
        public int userAddressPart1 { get; set; }
        public string lane { get; set; }
        public string alley { get; set; }
        public string addressNum { get; set; }
        public string addressF { get; set; }
        public string userRank { get; set; }
    
        public virtual streetName streetName { get; set; }
    }
}
